[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "atp"
version = "0.1.0"

[project.scripts]
atp = "cli:main"

[tool.setuptools]
py-modules = [
    "cli",
    "main",
    "skript",
]

include-package-data = true

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
configs = ["*.jsonc"]
data = ["**/*"]
skripts = ["**/*"]