[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "atp"
version = "0.1.0"

[project.scripts]
atp = "cli:main"

[tool.setuptools]
py-modules = [
    "cli",
    "main",
    "skript",
]

include-package-data = true

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
configs = ["*.jsonc"]
data = ["**/*"]
skripts = ["**/*"]
terminalGui = ["**/*"]
AnimePictures = ["**/*"]


[tool.setuptools.data-files]
"terminalGui" = ["terminalGui/menu.sh"]
"terminalGui/lib" = ["terminalGui/lib/*.sh"]
"terminalGui/menus" = ["terminalGui/menus/*.sh"]
"terminalGui/rofi" = ["terminalGui/rofi/*.rasi"]
"terminalGui/themes" = ["terminalGui/themes/*.rasi"]
"terminalGui/themes/wallust" = ["terminalGui/themes/wallust/*.rasi"]